"""Derive wire selectors from exact callsites; unresolved selectors never become rules."""
import json,struct,hashlib
from pathlib import Path
import capstone,pefile
ROOT=Path(__file__).resolve().parent

def selectors(catalog,engine):
    raw=engine.read_bytes()
    if hashlib.sha256(raw).hexdigest()!=catalog['engine_sha256']:raise ValueError('engine hash mismatch')
    pe=pefile.PE(data=raw,fast_load=True);base=pe.OPTIONAL_HEADER.ImageBase;md=capstone.Cs(capstone.CS_ARCH_X86,capstone.CS_MODE_32);out=[]
    for row in catalog['outbound_call_sites']:
        r=dict(name=row['name'],opcode=int(row['opcode'],16),extended=None,format=row['format'],call_va=row['call_va'])
        if r['opcode']==0xd0:
            start=int(row['method_va'],16);end=int(row['call_va'],16)
            ins=list(md.disasm(pe.get_data(start-base,end-start),start))
            # The c/h arguments are adjacent pushes immediately before the format.
            for i in range(len(ins)-1,0,-1):
                if ins[i].mnemonic=='push' and ins[i].op_str=='0xd0':
                    prev=ins[i-1]
                    if prev.mnemonic=='push':
                        try:r['extended']=int(prev.op_str,0)
                        except ValueError:pass
                    break
        out.append(r)
    return out

def main():
    src=json.loads((ROOT/'killer-reextracted.json').read_text());dst=json.loads((ROOT/'system-1-opcodes.json').read_text())
    source=selectors(src,ROOT.parent.parent/'system/engine.dll');target=selectors(dst,ROOT/'build/interlude-engine.dll')
    source_keys={(r['opcode'],r['extended']) for r in source if r['opcode']!=0xd0 or r['extended'] is not None}
    source_names={r['name'] for r in source}
    # Explicit C5/Interlude clan features absent in the C4 profile. Do not infer
    # that every absent export is unsupported: extraction is incomplete.
    interlude_features={
        'RequestPledgeMemberInfo','RequestPledgeMemberPowerInfo','RequestPledgePowerGradeList',
        'RequestPledgeReorganizeMember','RequestPledgeSetAcademyMasterPupil','RequestPledgeSetMemberPowerGrade','RequestPledgeWarList',
        'RequestPCCafeCouponUse','RequestExMagicSkillUseGround','RequestExMPCCShowPartyMembersInfo','RequestExFishRanking',
        'RequestCursedWeaponList','RequestCursedWeaponLocation','RequestGetBossRecord','RequestAskJoinPartyRoom','AnswerJoinPartyRoom',
        'RequestListPartyMatchingWaitingRoom','RequestExitPartyMatchingWaitingRoom','RequestExChangeName','RequestDuelStart',
        'RequestDuelAnswerStart','RequestConfirmTargetItem','RequestConfirmRefinerItem','RequestConfirmGemStone','RequestRefine',
        'RequestConfirmCancelItem','RequestRefineCancel','RequestDuelSurrender'}
    denied=[]
    for r in target:
        if r['name'] in interlude_features and r['name'] not in source_names and r['extended'] is not None and (r['opcode'],r['extended']) not in source_keys:
            denied.append(r)
    if {r['name'] for r in denied}!=interlude_features:raise ValueError('Unresolved or colliding Interlude selector; refuse policy generation')
    policy={'source_sha256':src['engine_sha256'],'target_sha256':dst['engine_sha256'],'source_selectors':source,'target_selectors':target,'denied':denied,'unknown_policy':'pass through and observe; absence from extraction does not prove incompatibility'}
    policy['denied_action_ids']={'opcode':'0x45','ids':list(range(1031,1041)),
        'evidence':'Exact source/target actionname-e DAT comparison; test_action_catalogue_blocks_only_interlude_summon_commands',
        'scope':'Interlude-only summon commands; source action IDs and unknown custom IDs retain their route. Local find-store and duel UI commands use their own native paths.'}
    (ROOT/'outbound-policy.json').write_text(json.dumps(policy,indent=2)+'\n')
    lines=['// Generated by derive_outbound_policy.py for the hash-gated profile.']
    for r in sorted(denied,key=lambda r:r['extended']):lines.append('    {0x%04x, "%s"},'%(r['extended'],r['name']))
    (ROOT/'native/outbound_denied.inc').write_text('\n'.join(lines)+'\n')
    print(json.dumps(denied,indent=2))
if __name__=='__main__':main()
